version: "3"

services:
  wnpos-web-php:
    build:
      context: './docker-php'
    working_dir: /var/www/laravel
    environment: 
      - "APP_ENV=dev"
      - "APP_DEBUG=true"
      - "DOMAIN_OWNER=owner.wnpos.local"
      - "DOMAIN_TEAM=team.wnpos.local"
      - "MASTER_DATA_DOMAIN=https://manage.foodstory.local:8080"
    volumes: 
      - ./:/var/www/laravel

  wnpos-web-nginx:
    build: ./docker-nginx
    container_name: nginx_wnpos
    working_dir: /var/www/laravel # directory ที่จะเป็นจัดที่เราทำงาน
    volumes_from: 
      - wnpos-web-php
    ports:
      - "80:80"

  wnpos-web-composer: # เป็น container สำหรับการรัน install package laravel ที่จะสั่งรันครั้งเดียวแล้วหยุดรัน container ไป
    build: ./docker-php # ใช้ dockerfile เดียวกันกับ container php
    working_dir: /var/www/laravel
    volumes_from:
      - wnpos-web-php
    command: "composer install"
